### ISSUE TITLE
Program will not start

### ISSUE THREAD

**Issue by CmdrRoot** [mgth/LittleBigMouse#103]
Seemed to break after the most recent windows update. Tried restarting, uninstalling and reinstalling the two most recent versions with no success.

**Comment by quasarea** [comment]
no KB4515384 in the system, can't run latest version, previous (which was old 4.1) were working fine

three entries in event log:
```
Application: LittleBigMouse_Daemon.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeLoadException
   at LittleBigMouse_Daemon.Program.Main(System.String[])
```

```
Faulting application name: LittleBigMouse_Daemon.exe, version: 4.0.7124.42680, time stamp: 0x5d1e72d0
Faulting module name: KERNELBASE.dll, version: 10.0.17134.1006, time stamp: 0x2a97fa2d
Exception code: 0xe0434352
Fault offset: 0x000000000003a388
Faulting process id: 0x6ee0
Faulting application start time: 0x01d578378452c7f0
Faulting application path: C:\Program Files\LittleBigMouse\LittleBigMouse_Daemon.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 60fe9e3e-e768-424f-8a4a-fb18630bacec
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket 1984630503640971654, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: LittleBigMouse_Daemon.exe
P2: 4.0.7124.42680
P3: 5d1e72d0
P4: KERNELBASE.dll
P5: 10.0.17134.1006
P6: 2a97fa2d
P7: e0434352
P8: 000000000003a388
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6240.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER62CD.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER62DE.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER62E6.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6316.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_LittleBigMouse_D_861a81d352b637f8c71b173763ced0896076a1a6_bbb52b3d_785e6731

Analysis symbol: 
Rechecking for solution: 0
Report Id: 60fe9e3e-e768-424f-8a4a-fb18630bacec
Report Status: 268435456
Hashed bucket: 352c97376f24ad973b8ad2ed93ecb986
Cab Guid: 0
```
[Report.zip](https://github.com/mgth/LittleBigMouse/files/3675391/Report.zip)

**Comment by janArb** [comment]
> 
> 
> uninstalled and went back to 4.2.7120.40854 that works fine

That older version doesn't work for me, too.

**Comment by Yeomans** [comment]
Exact same issue. Was using some version of 4.1 (can't remember which). Updated to Windows 10 1903. Continued to work. Updated to latest version and won't start. Tried previous version, same issue

**Comment by TheHungryGeek** [comment]
I have the same issue here as well, program will not load on startup.

**Comment by TheHungryGeek** [comment]
So I've managed to get it to load on startup without the UAC by following the steps at https://www.tenforums.com/tutorials/57690-create-elevated-shortcut-without-uac-prompt-windows-10-a.html

I just need to what I have to change (in particular, step 8), to get LBM to start minimised + enabled. Right now on startup it loads maximised and I have to manually click "apply" each time.

**Comment by ontogenez** [comment]
Same for me.

Event Viewer:
Application: LittleBigMouse_Control.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeLoadException
   at LittleBigMouse_Control.App.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at LittleBigMouse_Control.App.Main()








Further analysis with Fusion logging pointed to mscorlib.dll.


<meta http-equiv="Content-Type" content="charset=unicode-1-1-utf-8"><html><pre>
*** Assembly Binder Log Entry  (14.02.2020 @ 14:15:39) ***

The operation failed.
Bind result: hr = 0x80004005. Unspecified error

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Program Files\LittleBigMouse\LittleBigMouse_Control.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files/LittleBigMouse/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = LittleBigMouse_Control.exe
Calling assembly : HLab.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Rejecting native image because native image dependency C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected

</pre></html><meta http-equiv="Content-Type" content="charset=unicode-1-1-utf-8"><html><pre>
*** Assembly Binder Log Entry  (14.02.2020 @ 14:15:39) ***

The operation failed.
Bind result: hr = 0x80004005. Unspecified error

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Program Files\LittleBigMouse\LittleBigMouse_Control.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files/LittleBigMouse/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = LittleBigMouse_Control.exe
Calling assembly : HLab.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Rejecting native image because native image dependency C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Rejecting native image because native image dependency C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected

</pre></html><meta http-equiv="Content-Type" content="charset=unicode-1-1-utf-8"><html><pre>
*** Assembly Binder Log Entry  (14.02.2020 @ 14:15:39) ***

The operation was successful.
Bind result: hr = 0x1. Incorrect function.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Program Files\LittleBigMouse\LittleBigMouse_Control.exe
--- A detailed error log follows. 

BEGIN : Native image bind.
  LOG: Start validating all the dependencies.
  LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
  Dependency name: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  LOG: Start validating all the dependencies.
  LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
  Dependency name: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
END   : Incorrect function. (Exception from HRESULT: 0x00000001 (S_FALSE))

</pre></html><meta http-equiv="Content-Type" content="charset=unicode-1-1-utf-8"><html><pre>
*** Assembly Binder Log Entry  (14.02.2020 @ 14:15:39) ***

The operation failed.
Bind result: hr = 0x80004005. Unspecified error

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Program Files\LittleBigMouse\LittleBigMouse_Control.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files/LittleBigMouse/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = LittleBigMouse_Control.exe
Calling assembly : HLab.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Rejecting native image because native image dependency C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Rejecting native image because native image dependency C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected
WRN: No matching native image found.

</pre></html><meta http-equiv="Content-Type" content="charset=unicode-1-1-utf-8"><html><pre>
*** Assembly Binder Log Entry  (14.02.2020 @ 14:15:39) ***

The operation failed.
Bind result: hr = 0x80004005. Unspecified error

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Program Files\LittleBigMouse\LittleBigMouse_Control.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files/LittleBigMouse/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = LittleBigMouse_Control.exe
Calling assembly : HLab.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Rejecting native image because native image dependency C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected
LOG: Start validating all the dependencies.
LOG: [Level 1]Start validating native image dependency mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089.
Rejecting native image because native image dependency C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll had a different identity than expected
WRN: No matching native image found.

</pre></html>

**Comment by ontogenez** [comment]
Fixed the issue (followed instruction given in https://www.smrfoundation.org/forums/topic/error-encountered-after-windows-10-update/ ).

1. Uninstall LBM from Control Panel
2. Go to C:\Users\[user_profile_name]\AppData\Local\Apps\2.0
3. You should notice 2 folders: one is named “Data” and the other one has a strange name. The folder with the strange name used to have all the LBM files (now removed in step 1). Please try to delete that folder. If you are able to remove the folder, please try installing LBM again, otherwise continue in the next step
4. Open RegEdit and go to: [HKEY_LOCAL_MACHINE]\\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\
5. Under ProfileList find the profile that corresponds to your user. To do that click on the profile entry and check “ProfileImagePath” on the right side
6. After you have located your profile, add a new DWORD (32-bit) value entry name “RefCount” and set the Value to 0.(for more details you can check https://neosmart.net/wiki/corrupt-user-profile/)
7. Sign out from Windows (or restart)
8. Try installing LBM (it should work now!)
9. Open RegEdit again and remove the key (RefCount) you added in step 6

**Comment by Li-An** [comment]
Hello, I just installed for the first time LittleBigMouse and it’s not launched. Do  I have to follow Ontogenez tutorial ?

**Comment by PhillipMerritt** [comment]
The program starts, but all I get is a blurry rectangle on the screen before it crashes.
 
I followed all of the steps given by @ontogenez as well as 5 previous versions with no success.

I'm on Windows 10 Pro version 1903.
