### ISSUE TITLE
Gaming mode

### ISSUE THREAD

**Issue by StrikeByte** [mgth/LittleBigMouse#125]
Is it possible to add an gaming mode, because some games have issues when little big mouse is running

for example Valorant sometimes doesn't register clicks

**Comment by nilslorand** [comment]
It has problems with all UE games in Fullscreen

**Comment by jamesstidard** [comment]
I've experienced the same. If it could disable while full-screen is active (dunno if windows APIs can detect that) that would be great.

**Comment by GraemeWilde** [comment]
Hi, I also experience issues when playing games. It happens when I am turning in games, so moving the mouse to one side or the other. I will be turning, and then sometimes clicks will not register.

**Comment by MatthewBCooke** [comment]
Another issue I have in fullscreen applications is that when my mouse is on the side of my main display that connects to the next, the mouse will jump around on the border.

**Comment by Xenataur** [comment]
+1 to this, I have experienced this in Valorant and in League of Legends.

**Comment by jameslheard** [comment]
Yes this would be good, i think this effects most games.  To reproduce turn in a game while peforming action by holding a mouse button (firing for example in Deep Rock Galatic or using boosting in rocket league) once mouse cusor reaches what would be edge of screen (if it was visable) now release click. The action will continue as if you are still holding the mouse click, it I think its may be because LBM removes focus from game thus actions contines and gets stuck on until you click again returning focus to that window. 

I think the most easy fix (other than a true fix) would just be to disable if another app is running full screen, or possible a list of apps that should disable it. Remote desktop is consider a full screen applications I belive and would not want that to stop working with that as use across all three monitors, so if disabling for full screen app can you please make sure RDP continues to work with it. Thank you.

**Comment by notpbj** [comment]
+1 to this, issue experience in valorant whether running in fullscreen or windowed borderless

**Comment by VinceBT** [comment]
Please try this https://github.com/VinceBT/LBMM

**Comment by mgth** [comment]
You may now use Excluded.txt in $ProgamData\Mgth\LittleBigMouse to exclude some programs, just put a signifiant part of the path to exclude per line.
