### ISSUE TITLE
Issue with rotated display

### ISSUE THREAD

**Issue by vasilishomegas** [mgth/LittleBigMouse#139]
I am using a rotated 1080p monitor next two a regular 1440p and 4k monitor, but while the transition between the two regular monitors works fine, it somehow seems to match the top half of the 1440p to the bottom half of the 1080p, while the 1080p monitor (I guess the 1920p monitor if you like) is taller than the 1440p both in pixels as well as physical size.
![image](https://user-images.githubusercontent.com/10067714/92769316-21277000-f399-11ea-8437-88c81664f163.png)
When the 1080p was in its regular orientation, it worked as expected.

**Comment by fqdb** [comment]
I got the same issue, the mouse still acts like in the Windows settings, although LBM is setup correctly.

![image](https://user-images.githubusercontent.com/2826336/92994413-4e3f6400-f4fa-11ea-9413-60cc65db8355.png)

**Comment by robhunt3r** [comment]
I have your same setup
For me I can't get my mouse to enter the Monitor 3...
I can only enter that monitor if I enable Vertical Loop, go to Monitor 2 and move UPWARDS then the cursor will show up at the bottom of Monitor 3
??

**Comment by vasilishomegas** [comment]
Not sure why or how, but it seems to work correctly now. I didn't touch anything, but all transitions are correct for me at the moment.

**Comment by robhunt3r** [comment]
I found out the problem is the layout not changing at all, so app starts with this layout and no matter how many times I change it, if I reopen the app, same layout is applied.
Turns out, left screen is perfectly detected but it´s position isoverlapped, if I move the cursor to some corner it goes both screen 2 and 3, sometimes one, sometimes the other.
![image](https://user-images.githubusercontent.com/5111603/94309561-8faf2500-ff78-11ea-8df5-f33acc0230a8.png)

**Comment by 4nqyi** [comment]
Dont mess with the size setting to align the blue & beige bars. Adjust the location settings to form a rectangle canvas. Delete your registry keys and start over.

![image](https://user-images.githubusercontent.com/11065729/182792915-48ddd8e4-b41c-458c-acaa-f27391a66330.png)
