### ISSUE TITLE
Cannot snap to the edge of one monitor easily.

### ISSUE THREAD

**Issue by jcl4068** [mgth/LittleBigMouse#174]
When LittleBigMouse is started without ANY settings enabled, you already cannot snap to the shared edge between monitors anymore. Instead you pass through easily. The other functions are really nice but this is a deal breaker. 
Does anyone know of a work around for this? 
Is there a program to re-enable the sticky edge?

Thanks.

**Comment by aventum** [comment]
bump, same problem here

**Comment by andyspitze** [comment]
Yeah, it really is a deal breaker. Sadly this issue is known for years. I don't think this will ever get fixed. You will have to look for an alternative.

**Comment by thegodwalk** [comment]
Made a new account because I think I have a fix for this. Presuming you mean snapping windows to the shared edge, dual monitor tools offers a quick and easy fix by using system defined areas. I'm currently using ctrl/win+numpad shortcuts to assign windows to corresponding areas on either of my monitors. As an added bonus, this allows you to split windows vertically in portrait mode.
