### ISSUE TITLE
LBM application won't apply changes

### ISSUE THREAD

**Issue by Superkuiken** [mgth/LittleBigMouse#180]
I got an 29" 2560x1080 that I want to combine with a 24" 2560x1440 display. Both displays have the same physical height.
When trying to use LBM to scale the mouse transition and speed between the displays, I can't seem to apply the changes. When pressing the Apply button in the app, nothing seems to be happening

As visible in the picture, the changes are applied, but windows still sees the rightmost display as enormous compared to my larger UW. 

![LBM issue 1](https://user-images.githubusercontent.com/89300663/130319766-98cd6bf8-e057-4e95-8c2a-e7fe7fb669e3.JPG)

**Comment by Kiefy** [comment]
I think you are misunderstanding what LBM does.  It won't shrink displays in screenshots or w/e.
It specifically let's you tell your computer the physical sizes of your monitors, so that when the mouse pointer passes from one to the other, it appears exactly where it should, regardless of what resolutions each monitor has.

You should make the displays in LBM look exactly the same as what you would see if you took a pic of your monitors with a camera.
