### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by D5KDeutsche** [mgth/LittleBigMouse#183]
This doesn't play well with a clean install of Windows 11. When the program loads, the mouse will not work on the primary monitor, but works fine on the secondary. The system freezes as well, not allowing me to ctrl + alt + del or alt + f4.

**Comment by mdudek** [comment]
I have the same experience.

**Comment by GrotenM** [comment]
Same issue here. Also in other Threads no response of the devs. Sadly gonna uninstall it since it makes the pc unusable.

**Comment by bartvdbraak** [comment]
Did anyone find any alternatives?

**Comment by mivds** [comment]
For anyone else coming across this, it seems to work fine for me on Windows 11. I am using a clean install of Windows 11, on build 22000.318 with [LittleBigMouse 4.2.7124.42685](https://github.com/mgth/LittleBigMouse/releases/tag/4.2.7124.42685).

Not sure if anything changed on the Windows side since the reports above, but for those struggling with mouse annoyances it may be worth giving it another try.

**Comment by Sulexa** [comment]
Juste updated from windows 10 to 11 with little big mouse installed.
It seems to work perfectly on my side.

**Comment by architjaiswal** [comment]
> Does this imply Windows 11 STILL doesn't handle correct DPI difference between monitors? How disappointing...

That's a shame on microsoft/windows, being the reason why Apple Inc. still exists...
