### ISSUE TITLE
Problem with landscape flipped monitor alignment

### ISSUE THREAD

**Issue by LucaBoschetto** [mgth/LittleBigMouse#205]
Hi! Long time user of Little Big Mouse, a life saver for me.

Starting today, I will need to change my screens layout, so that I will have one of my screens used as a graphic tablet, and to do this I need to switch it to "landscape flipped".

Little big mouse correctly detects this, as shown by the upside down label on screen 1:

![image](https://user-images.githubusercontent.com/61137723/187465722-599be767-ec9b-4313-9f62-2a3e4d5d504a.png)

The problem is that, despite that and the fact that the screen alignment is quite correct (considering that one screen is basically horizontal):

![image](https://user-images.githubusercontent.com/61137723/187466899-8390208a-fe21-451b-bbd5-761f580f5ff0.png)

... the mouse doesn't respect that alignment: it jumps from screen 2, -2.9, to screen 1, +1.7 and from screen 2, -0.5 to screen 1, +4.2.

Any ideas for a workaround? Clearly, the best thing would be to have a fix, but I see that LBM is not under active development anymore... 😢

**Comment by 4nqyi** [comment]
1. Start fresh by resetting your settings.
  - Quit LBM and backup & delete your registry settings.  https://github.com/mgth/LittleBigMouse/issues/147
  - HKEY_CURRENT_USER\SOFTWARE\Mgth\LittleBigMouse
  - Restart LBM
2.  In the Size settings set all your borders to 1. 
  - Don't touch anything else in this screen it'll lead to unpredictable behavior.
![image](https://user-images.githubusercontent.com/11065729/187599841-673e5dbe-8883-4117-aff2-7a372a21690f.png)
3. In the Location settings drag your windows to how you want your mouse to move across monitors and start adjusting the screen sizes so that it forms a **square** canvas.
4. Click on Apply/Start and turn on the rulers to check your mouse movement across screens is in alignment.
![image](https://user-images.githubusercontent.com/11065729/187601379-dfe670fe-cd11-4d5c-8948-ff82dd91453b.png)
![image](https://user-images.githubusercontent.com/11065729/187603612-3fc4318c-3ef7-483e-81c8-fd6617fe89be.png)

For your setup I would set up the screen 1 so that the top border is split 50/50 between screen 2 & 3. That way you can easily move across the 3 screen no matter where your mouse pointer is.
![image](https://user-images.githubusercontent.com/11065729/187603877-0f2e8f29-83e6-49ed-b56c-4fcf33cbbd17.png)
