### ISSUE TITLE
Fullscreen game with different non-native resolution

### ISSUE THREAD

**Issue by sora987** [mgth/LittleBigMouse#209]
Hi,

I'm having problems with full screen game at non-native resolution.

For example, a full screen game at 1080p on a 4K monitor will have serious problem when moving mouse cursor from one screen to another.

Is there any way to make the program automatically adjust, or should I simply give up trying to find a solution for this problem?

Thanks

**Comment by stom66** [comment]
LBM doesn't play well with games. Best bet is to disable it while playing.

**Comment by SpeedRider** [comment]
it would be cool if it had an auto-scale.
like if the display gets set to 4k instead of 1440p in-game the display that changed gets auto-sized so it stays the same size as the other screen. so you still can move your mouse from one screen to the other. 
idk if it would be possible but would be amazing :D
