### ISSUE TITLE
LBM Daemon Constantly Asking For Permission To Make Changes

### ISSUE THREAD

**Issue by TooSpooky** [mgth/LittleBigMouse#211]
Hello,

I've had this issue with LBM while using LBMM that when playing a game at times, it will constantly spam me for permission to make changes to my computer every few minutes or more which takes my mouse out of the game completely. 

Seems to be specifically when telling it to stop or start.

Thanks for your time and take care!

**Comment by RhetoricalRabbit** [comment]
Currently, I've found a simple fix for this, as I had this issue as well. I haven't been able to find another fix. 

1. Search for "**User Account Control**" (UAC). It should pop up for **Change User Account Control Settings**.

2. Put the slider to **Never Notify** and save the changes. 

This will completely disable UAC. So I wouldn't recommend it for a long period of time. You may disable it for a small amount of time while you're gaming, then turn it back on when you're not doing so. Keeping it on is a good preventive measure against programs or sites you visit from making changes to your computer. I would still be looking for another alternative if possible. 

(Or maybe @mgth could possibly integrate blacklisted applications into LBM, instead of having LBMM execute a command through command prompt.)
