### ISSUE TITLE
Nice try motherfucker

### ISSUE THREAD

**Issue by rusnuker** [mgth/LittleBigMouse#229]
Epic fail :P
![image](https://user-images.githubusercontent.com/49472785/210543110-691cfe96-1582-433d-8bb6-681ce9b7905b.png)

**Comment by argo0n** [comment]
> Nice try motherfucker

Maybe consider that you're using a Windows version too old for this app and you're the one who broke it! Or that you didn't follow the instructions to uninstall it properly!

Don't go calling people "motherfucker" if you're the idiot who can't understand programs have unintended bugs caused by stupidity of the user.

**Comment by BrentNewland** [comment]
Windows 10/11 **ONLY**
