### ISSUE TITLE
Possible infection

### ISSUE THREAD

**Issue by RickOpGit** [mgth/LittleBigMouse#244]
According to:

https://www.virustotal.com/gui/file/5760b36b506de39cbf8855f3947c57bd742175fed7560023e5d42639ce280d8a/summary

The file is infected.

This is the only program i had installed on a clean windows install when my session tokens were stolen and steam purchases were made without any 2FA.

**Comment by BrentNewland** [comment]
According to your link, only 1 app flagged it, "CrowdStrike Falcon". When no-name random 3rd party virus scanners flag a file, and no one else does, it's a false positive.

**Comment by HunterAP23** [comment]
> According to your link, only 1 app flagged it, "CrowdStrike Falcon". When no-name random 3rd party virus scanners flag a file, and no one else does, it's a false positive.

I wouldn't call CrowdStrike some no name app, its an enterprise AV and security tool used by most f the bigger tech companies like Amazon.
But that being said, the report and the community comments left on that VirusTotal report are leaning more towards "suspicious" rather than saying that it's malicious outright.
