### ISSUE TITLE
how to undo detach?????

### ISSUE THREAD

**Issue by Eyeof** [mgth/LittleBigMouse#312]
I accidently clicked "Detach" on the BigLittleMouse software and now my 2nd monitor will not detect at all, I've tried to uninstall BigLittleMouse and restart my displays but nothing works.

**Comment by mgth** [comment]
Just add it to desktop from Display Settings

**Comment by KaiaSage** [comment]
I needed to close and exit LBM, then reopen it to replace the "Detatch" button with "Attach"

**Comment by draco1738** [comment]
im encountering the same issue, i restarted LBM and clicked the "attach" button, but all it does it change the resolution of the working monitor to that of the monitor that wont display picture. and it also raises the refresh rate of the non working monitor beyond its max... ive gone through 4 versions of LBM, restarted my pc, did a driver refresh adn download.. nothing is working

**Comment by Spencer-tull** [comment]
> im encountering the same issue, i restarted LBM and clicked the "attach" button, but all it does it change the resolution of the working monitor to that of the monitor that wont display picture. and it also raises the refresh rate of the non working monitor beyond its max... ive gone through 4 versions of LBM, restarted my pc, did a driver refresh adn download.. nothing is working

Same thing is happening to me, my monitor is just non stop flashing black and in display settings the monitor I detached now says “disconnect this display” under the multiple displays tab and in the view of my monitors it’s a tiny square. PLEASE HELP IT WONT STOP AND NOTHING I DO IN THE SOFTWARE FIXES IT!!!

**Comment by Spencer-tull** [comment]
> im encountering the same issue, i restarted LBM and clicked the "attach" button, but all it does it change the resolution of the working monitor to that of the monitor that wont display picture. and it also raises the refresh rate of the non working monitor beyond its max... ive gone through 4 versions of LBM, restarted my pc, did a driver refresh adn download.. nothing is working

Got it to work, I had to go into display settings and change the monitor to duplicate desktop on 1 and 2 so that it would just show up as a duplicate of a different display. Then after that I could change that merged duplicated monitor back to extend displays onto 1 and 2 or whatever numbers you chose and that fixed it!

**Comment by mgth** [comment]
This should be fixed by #476, which will be part of the next release.

**Root cause**: once a monitor is detached from the desktop, Windows enumerates it as a *binding candidate* under every inactive adapter output, so the `\\.\DISPLAYn` device name LittleBigMouse used to designate it no longer identifies that monitor. Clicking Attach could therefore activate the wrong monitor (with several monitors detached, they all reported the same device name), and the stored display mode was applied to whatever monitor the driver picked — hence black screens, wrong resolution or refresh rate, and Attach appearing to do nothing. This was reproduced and verified on hardware.

Attach and detach now designate the monitor by its device identity through the Windows CCD API (`SetDisplayConfig`), so the right monitor is targeted regardless of how many are detached. In addition, #475 added a confirmation dialog before detaching/attaching, explaining the consequences and the recovery steps.

**Until the next release**, if a monitor is stuck detached: right-click the desktop → Display settings, select the detached monitor and choose "Extend desktop to this display" under Multiple displays (or press Win+P and choose Extend). If the monitor is not listed, click "Detect other display".
