### ISSUE TITLE
Different size of windows

### ISSUE THREAD

**Issue by Fimmel1** [mgth/LittleBigMouse#336]
Hello,

I just found the program. I really like it!

I use a 4k monitor and to it's left a WQHD monitor. Both are 32". 
But now when I move a window between both monitors the size is completely off.

The right one is the 4k, the left is WQHD
![IMG_1071](https://github.com/mgth/LittleBigMouse/assets/83457170/319f204a-2bd4-44c2-8ac1-594f57550189)

Is there any fix?

Thanks!

**Comment by mgth** [comment]
Hello, the soft does not take care of window size. It is a Windows behavior, and it is the same without LittleBigMouse installed. 
The window get resized to the right dpi when most of it has reach the second monitor. Did you try it before ?

**Comment by Fimmel1** [comment]
Yes, exactly. When i think 66% of the window is on the new screen, it get scaled properly. Is there any fix to this? Any other software?

Thanks

**Comment by mgth** [comment]
I'm not aware of any. I think the problem is quite difficult. For dpi aware applications, this is not a simple bitmap resize, but the content is rearranged according to new resolution. It would require to have two instance of the same window. And for the app two states (or more if many monitors) for each control. An "easy" solution would be to resample the small part as it is with non dpi aware apps. But I dont see an easy solution without being Microsoft.
