### ISSUE TITLE
LBM not adding startup item to Task Scheduler

### ISSUE THREAD

**Issue by YangVincent** [mgth/LittleBigMouse#72]
How can I set the daemon to start? Alternatively, is there a command line argument to pass in to have it running and "start" selected by default?

**Comment by Quip13** [comment]
Create a shortcut for LBM daemon and append --start to the shortcut target
e.g. Target: "C:\Program Files\LittleBigMouse\LittleBigMouse_Daemon.exe" --start

Place that shortcut in your windows startup folder, found here:
C:\Users\<user name>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup

**Comment by mgth** [comment]
Yes but then the daemon won't get admin privileges and it will get disabled whenever an elevated process will get the focus.
That's why i used Task Scheduler in first place.
But you still can create the task by hand with the same command line : 
"C:\Program Files\LittleBigMouse\LittleBigMouse_Daemon.exe" --start
and tick "Run with the highest privileges"

**Comment by DaveB1977** [comment]
adding comment to this ticket as it seems closest to my (new) issue. Been yusing TS to run LBM fine for year, seems the 20H2 update broke it, and quite badly. It's taken me a lot of tweaking to get the task to stop showing disabled, which it did at every log in. Now it shows "Ready" but will not run automatically no matter what I try, I can either run using the shortcut provided in another ticket or open TS and manually run it, either of which gets it working. 

I've tried uninstalling and re-doing with the layest release, no luck. Any ideas?
